In [129]:
import torch

## x_1 * x_2

In [55]:
x = torch.randint(1,30,(10000, 2)).type(torch.FloatTensor)
y = torch.stack([torch.tensor(x_1*x_2) for [x_1,x_2] in x])
num_train = int(len(x)*2/3)
train_x,train_y = x[:num_train,:],y[:num_train]
test_x,test_y = x[num_train:,:],y[num_train:]

/Users/tokunagamasaomi/.pyenv/versions/3.7.0/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


In [125]:
net = torch.nn.Sequential(
    torch.nn.Linear(2,16),
    torch.nn.ReLU(),
    torch.nn.Linear(16,8),
#     torch.nn.ReLU(),
#     torch.nn.Linear(2,1)
    torch.nn.ReLU(),
    torch.nn.Linear(8,1)
)

criterion = torch.nn.MSELoss()
optimizer = torch.optim.Adam(net.parameters(),lr=3e-3)

In [126]:
# import tqdm
num_epochs = 10
# c = 0.
for epoch in range(1,num_epochs+1):
    l = 0.
    for data,label in zip(train_x,train_y):
        net.train()

        optimizer.zero_grad()
        output = net(data)
        loss = criterion(output, label)
        loss.backward()
        optimizer.step()

        l += loss.item()
        #     c += 1 if output == label else 0

    print("Epoch {}: Loss: {:.4f}".format(epoch,l/len(train_x)))
    
    l = 0.
    for data, label in zip(test_x, test_y):
        net.eval()
        with torch.no_grad():
            output = net(data)
            loss = criterion(output, label)
            
        l += loss.item()
        
    print("Val: Loss: {:.4f}".format(l/len(test_x)))

Epoch 1: Loss: 12044.9853
Val: Loss: 1597.8493
Epoch 2: Loss: 1087.3095
Val: Loss: 581.5103
Epoch 3: Loss: 578.2425
Val: Loss: 430.6457
Epoch 4: Loss: 450.3344
Val: Loss: 331.8509
Epoch 5: Loss: 328.8659
Val: Loss: 239.6527
Epoch 6: Loss: 214.0399
Val: Loss: 160.6423
Epoch 7: Loss: 146.6613
Val: Loss: 101.0157
Epoch 8: Loss: 123.0485
Val: Loss: 90.6527
Epoch 9: Loss: 111.6339
Val: Loss: 80.3632
Epoch 10: Loss: 103.7948
Val: Loss: 76.6925
Epoch 11: Loss: 98.1081
Val: Loss: 71.7017
Epoch 12: Loss: 81.6216
Val: Loss: 55.1896
Epoch 13: Loss: 67.8575
Val: Loss: 36.7047
Epoch 14: Loss: 61.1177
Val: Loss: 33.0022
Epoch 15: Loss: 56.6037
Val: Loss: 29.2205
Epoch 16: Loss: 53.9184
Val: Loss: 28.1211
Epoch 17: Loss: 51.6554
Val: Loss: 26.1722
Epoch 18: Loss: 50.4923
Val: Loss: 24.8787
Epoch 19: Loss: 49.1769
Val: Loss: 24.9610
Epoch 20: Loss: 47.8909
Val: Loss: 25.4612
Epoch 21: Loss: 47.0275
Val: Loss: 23.8775
Epoch 22: Loss: 45.7255
Val: Loss: 25.4198
Epoch 23: Loss: 44.3590
Val: Loss: 27.4259

KeyboardInterrupt: 

In [111]:
net(torch.tensor([80,20.]))

tensor([8.5928], grad_fn=<AddBackward0>)

In [114]:
class PosLog(torch.nn.Module):
    def __init__(self):
        super(PosLog,self).__init__()
        
    def forward(self, x):
        zeros = torch.zeros_like(x)
        return torch.where(x>0,torch.log(x),zeros)
    
class Exp(torch.nn.Module):
    def __init__(self):
        super(Exp,self).__init__()
        
    def forward(self,x):
        return torch.exp(x)
        
net = torch.nn.Sequential(
    torch.nn.Linear(2,16),
    PosLog(),
    torch.nn.Linear(16,8),
    Exp(),
    torch.nn.Linear(8,1)
)

lr = 3e-4

criterion = torch.nn.MSELoss()
optimizer = torch.optim.Adam(net.parameters(),lr=lr)

In [115]:
# import tqdm
num_epochs = 10
l_min = float("inf")
# c = 0.
for epoch in range(1,num_epochs+1):
    l = 0.
    for data,label in zip(train_x,train_y):
        net.train()

        optimizer.zero_grad()
        output = net(data)
        loss = criterion(output, label)
        loss.backward()
        optimizer.step()

        l += loss.item()
        #     c += 1 if output == label else 0

    print("Epoch {}: Loss: {:.4f}".format(epoch,l/len(train_x)))
    
    l = 0.
    for data, label in zip(test_x, test_y):
        net.eval()
        with torch.no_grad():
            output = net(data)
            loss = criterion(output, label)
            
        l += loss.item()
        
    if l < l_min:
        print("set net!")
        l_min = l
        min_net = copy.deepcopy(net)
        
    print("Val: Loss: {:.4f}".format(l/len(test_x)))

Epoch 1: Loss: 11634.6344
set net!
Val: Loss: 527.7053
Epoch 2: Loss: 179.0129
set net!
Val: Loss: 55.3564
Epoch 3: Loss: 63.8768
set net!
Val: Loss: 54.2901
Epoch 4: Loss: 34.6135
set net!
Val: Loss: 18.7632
Epoch 5: Loss: 32.0313
Val: Loss: 36.6153
Epoch 6: Loss: 27.7576
set net!
Val: Loss: 14.9711
Epoch 7: Loss: 21.1694
Val: Loss: 15.9908
Epoch 8: Loss: 23.7410
set net!
Val: Loss: 9.1980
Epoch 9: Loss: 20.0086
Val: Loss: 19.8688
Epoch 10: Loss: 12.4639
set net!
Val: Loss: 5.2778


In [117]:
min_net(torch.tensor([80.,30.]))

tensor([2482.7644], grad_fn=<AddBackward0>)

## x_1 + x_2 + x_1 * x_2

In [131]:
x = torch.randint(1,30,(10000, 2)).type(torch.FloatTensor)
y = torch.stack([torch.tensor(x_1+x_2+x_1*x_2) for [x_1,x_2] in x])
num_train = int(len(x)*2/3)
train_x,train_y = x[:num_train,:],y[:num_train]
test_x,test_y = x[num_train:,:],y[num_train:]

/Users/tokunagamasaomi/.pyenv/versions/3.7.0/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


In [136]:

net = torch.nn.Sequential(
    torch.nn.Linear(2,16),
    torch.nn.ReLU(),
    torch.nn.Linear(16,8),
#     torch.nn.ReLU(),
#     torch.nn.Linear(2,1)
    torch.nn.ReLU(),
    torch.nn.Linear(8,1)
)

criterion = torch.nn.MSELoss()
optimizer = torch.optim.Adam(net.parameters(),lr=3e-3)

# import tqdm
num_epochs = 10
# c = 0.
for epoch in range(1,num_epochs+1):
    l = 0.
    for data,label in zip(train_x,train_y):
        net.train()

        optimizer.zero_grad()
        output = net(data)
        loss = criterion(output, label)
        loss.backward()
        optimizer.step()

        l += loss.item()
        #     c += 1 if output == label else 0

    print("Epoch {}: Loss: {:.4f}".format(epoch,l/len(train_x)))
    
    l = 0.
    for data, label in zip(test_x, test_y):
        net.eval()
        with torch.no_grad():
            output = net(data)
            loss = criterion(output, label)
            
        l += loss.item()
        
    print("Val: Loss: {:.4f}".format(l/len(test_x)))

Epoch 1: Loss: 4798.1226
Val: Loss: 1155.7575
Epoch 2: Loss: 687.7025
Val: Loss: 354.7247
Epoch 3: Loss: 283.8792
Val: Loss: 293.1387
Epoch 4: Loss: 166.6305
Val: Loss: 120.7449
Epoch 5: Loss: 136.9444
Val: Loss: 89.0698
Epoch 6: Loss: 125.0764
Val: Loss: 173.4915
Epoch 7: Loss: 120.2337
Val: Loss: 143.1009
Epoch 8: Loss: 109.9115
Val: Loss: 267.7850
Epoch 9: Loss: 98.3847
Val: Loss: 296.7559
Epoch 10: Loss: 96.0563
Val: Loss: 253.5187


In [132]:
class PosLog(torch.nn.Module):
    def __init__(self):
        super(PosLog,self).__init__()
        
    def forward(self, x):
        zeros = torch.zeros_like(x)
        return torch.where(x>0,torch.log(x),zeros)
    
class Exp(torch.nn.Module):
    def __init__(self):
        super(Exp,self).__init__()
        
    def forward(self,x):
        return torch.exp(x)
        
net = torch.nn.Sequential(
    torch.nn.Linear(2,16),
    PosLog(),
    torch.nn.Linear(16,8),
    Exp(),
    torch.nn.Linear(8,1)
)

lr = 3e-4

criterion = torch.nn.MSELoss()
optimizer = torch.optim.Adam(net.parameters(),lr=lr)

# import tqdm
num_epochs = 10
l_min = float("inf")
# c = 0.
for epoch in range(1,num_epochs+1):
    l = 0.
    for data,label in zip(train_x,train_y):
        net.train()

        optimizer.zero_grad()
        output = net(data)
        loss = criterion(output, label)
        loss.backward()
        optimizer.step()

        l += loss.item()
        #     c += 1 if output == label else 0

    print("Epoch {}: Loss: {:.4f}".format(epoch,l/len(train_x)))
    
    l = 0.
    for data, label in zip(test_x, test_y):
        net.eval()
        with torch.no_grad():
            output = net(data)
            loss = criterion(output, label)
            
        l += loss.item()
        
    if l < l_min:
        print("set net!")
        l_min = l
        min_net = copy.deepcopy(net)
        
    print("Val: Loss: {:.4f}".format(l/len(test_x)))

Epoch 1: Loss: 7972.5173
set net!
Val: Loss: 115.9319
Epoch 2: Loss: 45.0892
set net!
Val: Loss: 25.1929
Epoch 3: Loss: 19.9456
set net!
Val: Loss: 21.1416
Epoch 4: Loss: 14.2337
set net!
Val: Loss: 14.9519
Epoch 5: Loss: 11.8240
set net!
Val: Loss: 12.8000
Epoch 6: Loss: 10.8230
set net!
Val: Loss: 11.5280
Epoch 7: Loss: 9.8705
set net!
Val: Loss: 6.5083
Epoch 8: Loss: 8.6705
set net!
Val: Loss: 4.9333
Epoch 9: Loss: 8.3882
set net!
Val: Loss: 4.1149
Epoch 10: Loss: 7.3028
set net!
Val: Loss: 3.0981


In [135]:
min_net(torch.tensor([50.,2.]))

tensor([149.9834], grad_fn=<AddBackward0>)

## F_5

In [158]:
# x = torch.randint(0,1,(10000, 10)).type(torch.FloatTensor)
x = torch.FloatTensor(10000, 10).uniform_(0,1)
y = torch.stack([torch.tensor((1/(1+x_1**2 + x_2**2 + x_3**2)) + torch.sqrt(torch.exp(x_4+x_5)) + torch.abs(x_6 + x_7) + x_8*x_9*x_10 ) for [x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,x_10] in x])
num_train = int(len(x)*2/3)
train_x,train_y = x[:num_train,:],y[:num_train]
test_x,test_y = x[num_train:,:],y[num_train:]

/Users/tokunagamasaomi/.pyenv/versions/3.7.0/lib/python3.7/site-packages/ipykernel_launcher.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  This is separate from the ipykernel package so we can avoid doing imports until


In [163]:

net = torch.nn.Sequential(
    torch.nn.Linear(10,256),
    torch.nn.ReLU(),
    torch.nn.Linear(256,128),
#     torch.nn.ReLU(),
#     torch.nn.Linear(2,1)
    torch.nn.ReLU(),
    torch.nn.Linear(128,64),
    torch.nn.ReLU(),
    torch.nn.Linear(64,1)
)

criterion = torch.nn.MSELoss()
optimizer = torch.optim.Adam(net.parameters(),lr=3e-3)

# import tqdm
num_epochs = 100
# c = 0.
for epoch in range(1,num_epochs+1):
    l = 0.
    for data,label in zip(train_x,train_y):
        net.train()

        optimizer.zero_grad()
        output = net(data)
        loss = criterion(output, label)
        loss.backward()
        optimizer.step()

        l += loss.item()
        #     c += 1 if output == label else 0

    print("Epoch {}: Loss: {:.4f}".format(epoch,l/len(train_x)))
    
    l = 0.
    for data, label in zip(test_x, test_y):
        net.eval()
        with torch.no_grad():
            output = net(data)
            loss = criterion(output, label)
            
        l += loss.item()
        
    print("Val: Loss: {:.4f}".format(l/len(test_x)))

Epoch 1: Loss: 0.0369
Val: Loss: 0.0864
Epoch 2: Loss: 0.0097
Val: Loss: 0.0121
Epoch 3: Loss: 0.0061
Val: Loss: 0.0069
Epoch 4: Loss: 0.0044
Val: Loss: 0.0016
Epoch 5: Loss: 0.0037
Val: Loss: 0.0010
Epoch 6: Loss: 0.0033
Val: Loss: 0.0011
Epoch 7: Loss: 0.0029
Val: Loss: 0.0007
Epoch 8: Loss: 0.0028
Val: Loss: 0.0012
Epoch 9: Loss: 0.0023
Val: Loss: 0.0006
Epoch 10: Loss: 0.0021
Val: Loss: 0.0006
Epoch 11: Loss: 0.0019
Val: Loss: 0.0008
Epoch 12: Loss: 0.0018
Val: Loss: 0.0007
Epoch 13: Loss: 0.0017
Val: Loss: 0.0008
Epoch 14: Loss: 0.0015
Val: Loss: 0.0010
Epoch 15: Loss: 0.0015
Val: Loss: 0.0006
Epoch 16: Loss: 0.0014
Val: Loss: 0.0011
Epoch 17: Loss: 0.0014
Val: Loss: 0.0010
Epoch 18: Loss: 0.0014
Val: Loss: 0.0006
Epoch 19: Loss: 0.0013
Val: Loss: 0.0007
Epoch 20: Loss: 0.0012
Val: Loss: 0.0006
Epoch 21: Loss: 0.0012
Val: Loss: 0.0006
Epoch 22: Loss: 0.0012
Val: Loss: 0.0007
Epoch 23: Loss: 0.0011
Val: Loss: 0.0006
Epoch 24: Loss: 0.0011
Val: Loss: 0.0006
Epoch 25: Loss: 0.0011
Va

In [164]:
class PosLog(torch.nn.Module):
    def __init__(self):
        super(PosLog,self).__init__()
        
    def forward(self, x):
        zeros = torch.zeros_like(x)
        return torch.where(x>0,torch.log(x),zeros)
    
class Exp(torch.nn.Module):
    def __init__(self):
        super(Exp,self).__init__()
        
    def forward(self,x):
        return torch.exp(x)
        
net = torch.nn.Sequential(
    torch.nn.Linear(10,256),
    PosLog(),
    torch.nn.Linear(256,128),
    Exp(),
    torch.nn.Linear(128,64),
    torch.nn.ReLU(),
    torch.nn.Linear(64,1)
)

lr = 3e-4

criterion = torch.nn.MSELoss()
optimizer = torch.optim.Adam(net.parameters(),lr=lr)

# import tqdm
num_epochs = 100
l_min = float("inf")
# c = 0.
for epoch in range(1,num_epochs+1):
    l = 0.
    for data,label in zip(train_x,train_y):
        net.train()

        optimizer.zero_grad()
        output = net(data)
        loss = criterion(output, label)
        loss.backward()
        optimizer.step()

        l += loss.item()
        #     c += 1 if output == label else 0

    print("Epoch {}: Loss: {:.4f}".format(epoch,l/len(train_x)))
    
    l = 0.
    for data, label in zip(test_x, test_y):
        net.eval()
        with torch.no_grad():
            output = net(data)
            loss = criterion(output, label)
            
        l += loss.item()
        
    if l < l_min:
        print("set net!")
        l_min = l
        min_net = copy.deepcopy(net)
        
    print("Val: Loss: {:.4f}".format(l/len(test_x)))

Epoch 1: Loss: 0.1085
set net!
Val: Loss: 0.0238
Epoch 2: Loss: 0.0401
set net!
Val: Loss: 0.0211
Epoch 3: Loss: 0.0244
Val: Loss: 0.0663
Epoch 4: Loss: 0.0164
set net!
Val: Loss: 0.0088
Epoch 5: Loss: 0.0111
set net!
Val: Loss: 0.0060
Epoch 6: Loss: 0.0073
set net!
Val: Loss: 0.0030
Epoch 7: Loss: 0.0051
Val: Loss: 0.0031
Epoch 8: Loss: 0.0040
set net!
Val: Loss: 0.0026
Epoch 9: Loss: 0.0038
Val: Loss: 0.0098
Epoch 10: Loss: 0.0042
Val: Loss: 0.0256
Epoch 11: Loss: 0.0034
Val: Loss: 0.0152
Epoch 12: Loss: 0.0034
Val: Loss: 0.0038
Epoch 13: Loss: 0.0031
Val: Loss: 0.0051
Epoch 14: Loss: 0.0028
Val: Loss: 0.0096
Epoch 15: Loss: 0.0026
set net!
Val: Loss: 0.0021
Epoch 16: Loss: 0.0027
Val: Loss: 0.0035
Epoch 17: Loss: 0.0023
Val: Loss: 0.0065
Epoch 18: Loss: 0.0024
Val: Loss: 0.0068
Epoch 19: Loss: 0.0023
Val: Loss: 0.0039
Epoch 20: Loss: 0.0019
Val: Loss: 0.0030
Epoch 21: Loss: 0.0018
Val: Loss: 0.0034
Epoch 22: Loss: 0.0017
set net!
Val: Loss: 0.0012
Epoch 23: Loss: 0.0019
Val: Loss: 0